server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mygame?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

mybatis-plus:
  global-config:
    db-config:
      table-underline: true # 数据库表名采用下划线命名与实体类匹配默认true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
    map-underscore-to-camel-case: false # 数据库表字段采用下划线命名与实体类匹配默认true
mygame:
  jwt:
    keyPairName: jwt.jks
    keyPairAlias: jwt
    keyPairSecret: 123456
    keyPairStoreSecret: 123456

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000


